### ISSUE TITLE
Delete chapters / content 

### ISSUE THREAD

**Issue by MelBourbon** [Wilhelmsson177/tonie-api#2]
It seems it's currently not possible to delete chapters or content on a Tonie. Correct? Is there any way to implement this?

**Comment by MelBourbon** [comment]
Seems to be possible with `​/households​/{household_pk}​/creativetonies​/{id}` `households_creativetonies_partial_update` and "Set "chapters" to [] (empty array) to clear the Creative-Tonie."

But I have no clue how to implement as I'm struggling with understanding your code.

**Comment by moritzj29** [comment]
Hello and thanks for your interest in my code!
Well, it is possible to delete content but it is not very obvious I confess. As far as I understand the original API, all the changes to the content of a creative tonie are done with a PATCH request against `/households​/{household_pk}​/creativetonies​/{id}`, as you suggested. In order to remove a chapter you have to get the content (IDs, titles, etc. not files) from the cloud, modify it and upload the content with the chapter removed.

In the scope of this python library, this is done with methods of the `_CreativeTonie` class. You retrieve the current content with the `.chapters` property. Modify this dict as you like, e.g. remove a chapter. Then you can update the tonie by calling the private method `._patch_chapters(chapters)` and pass the modified chapter dict. I made this method private since there are no checks, whether the chapters you pass are in a correct form. So it is possible to clear your entire tonie by passing a wrong chapters parameter.
Another way would be to just pass a list of chapter ids `id_list` to the `.sort_chapters('id',sortlist=id_list)`. The content of the tonie gets sorted according to that list and all content that is not part of the list is removed.

Of course one could add a method that just removes a chapter with a given id, going one of the two ways stated above. In my usecase I did not need it so far.

If you have any questions, I will try my best to help. I'm currently not using the project since my tonie_sync project relies on spotify-dowloader which only gets content from youtube. Unfortunately that does not work reliably for all the kids content in my usecase...

**Comment by moritzj29** [comment]
I also realized that the readthedocs documentation does not build for the API. I will try to fix this soon

**Comment by MelBourbon** [comment]
@moritzj29 Thanks. I will try to create a local branch and check if I update the code to fit to my need. The concern you have that the whole content is removed is no issue for me. I only need the functionality to clear the whole tonie. I'm using your library together with https://github.com/An0nimia/deezloader to sync playlists from deezer to my tonies. I use this for the same reason as you as syncing spotify through youtube is not very reliable. Maybe check if this fits to your needs as well. For me it's working great, the only thing missing is clearing the tonie before uploading which I currently still need to do manually.

**Comment by moritzj29** [comment]
this looks interesting, indeed...
if you just want to clear the whole tonie, I think calling `._patch_chapters([])` should do the trick.
In my spotifysync code I just odered according to the spotify playlist, so everything not on the playlist is removed automatically.
